/run/useMaximumLogicalCores
#/run/numberOfThreads 6
/run/initialize
/control/verbose 2
/run/verbose 2
/analysis/setFileName G4_Be9dn_LowE.root

/gps/particle neutron

# the incident surface is in the x-y plane
/gps/pos/rot1 0 1 0
/gps/pos/rot2 1 0 0
#
# the beam spot is centered at the origin and is
# of 1d gaussian shape with a 3mm central plateau
/gps/pos/shape Circle
/gps/pos/centre 0. 0. 0. mm
/gps/pos/radius 1.5875 mm
/gps/pos/sigma_r 0 mm
#
# the beam is travelling along the z-axis with 5 degrees dispersion
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0
/gps/ang/type beam1d
#/gps/ang/sigma_r 0.018257970943255358 rad
/gps/ang/sigma_r 0.0273719346404061 rad


/gps/ene/type Arb
/gps/hist/type arb
/gps/hist/point 0.025 1
/gps/hist/point 0.03 1
/gps/hist/point 0.035 1
/gps/hist/point 0.04 1
/gps/hist/point 0.045 1
/gps/hist/point 0.05 1
/gps/hist/point 0.055 1
/gps/hist/point 0.06 1
/gps/hist/point 0.065 1
/gps/hist/point 0.07 1
/gps/hist/point 0.075 1
/gps/hist/point 0.08 1
/gps/hist/point 0.085 1
/gps/hist/point 0.09 1
/gps/hist/point 0.095 1
/gps/hist/point 0.1 1
/gps/hist/point 0.105 1
/gps/hist/point 0.11 1
/gps/hist/point 0.115 1
/gps/hist/point 0.12 1
/gps/hist/point 0.125 1
/gps/hist/point 0.13 1
/gps/hist/point 0.135 1
/gps/hist/point 0.14 1
/gps/hist/point 0.145 1
/gps/hist/point 0.15 1
/gps/hist/point 0.2 1
/gps/hist/point 0.25 1
/gps/hist/point 0.3 1
/gps/hist/point 0.35 1
/gps/hist/point 0.4 1
/gps/hist/point 0.45 1
/gps/hist/point 0.5 1
/gps/hist/point 0.55 1
/gps/hist/point 0.6 1
/gps/hist/point 0.65 1
/gps/hist/point 0.7 1
/gps/hist/point 0.75 1
/gps/hist/point 0.8 1
/gps/hist/point 0.85 1
/gps/hist/point 0.9 1
/gps/hist/point 0.95 1
/gps/hist/point 1 1
/gps/hist/point 1.05 1
/gps/hist/point 1.1 1
/gps/hist/point 1.15 1
/gps/hist/point 1.2 1
/gps/hist/point 1.25 1
/gps/hist/point 1.3 1
/gps/hist/point 1.35 1
/gps/hist/point 1.4 1
/gps/hist/point 1.45 1
/gps/hist/point 1.5 1
/gps/hist/inter Lin
/run/printProgress 100000
/run/beamOn 2000000
