#!/bin/bash

for RU in {1..10}
do
    ./neutron_backgrounds Uniform_Ddn_6m.mac | ts '[%m-%d-%Y %H:%M:%S]'
    mv G4_Ddn_6m_Backgrounds.root G4_Ddn_6m_Backgrounds_$RU.root | ts '[%m-%d-%Y %H:%M:%S]'
    echo "File G4_Ddn_6m_Backgrounds_$RU.root now exists" | ts '[%m-%d-%Y %H:%M:%S]'
done

