#!/bin/bash

for RU in {1..10}
do
    ./neutron_backgrounds Uniform_Backgrounds_6m.mac | ts '[%m-%d-%Y %H:%M:%S]'
    mv G4_Background_6m.root G4_Background_6m_$RU.root | ts '[%m-%d-%Y %H:%M:%S]'
    echo "File G4_Background_6m_$RU.root now exists" | ts '[%m-%d-%Y %H:%M:%S]'
done