# Macro file for example B1
# 
# To be run preferably in batch, without graphics:
# % exampleB1 run2.mac
#
#/run/numberOfThreads 16
/analysis/setFileName en_{eKin}.root
/run/initialize
#
#/control/verbose 2
#/run/verbose 2
#
# gamma 6 MeV to the direction (0.,0.,1.)
# 10000 events
#
/gun/particle neutron
/gun/energy {eKin} MeV
/run/printProgress 1000000
/run/beamOn 10000000

#/gun/particle neutron
#/gun/energy 3.1 MeV
#/run/printProgress 100
#/run/beamOn 20000
# 
# proton 210 MeV to the direction (0.,0.,1.)
# 1000 events
#
#/gun/particle proton
#/gun/energy 210 MeV
#/run/printProgress 100
#/run/beamOn 100
