/run/useMaximumLogicalCores
#/run/numberOfThreads 6
/run/initialize
/control/verbose 2
/run/verbose 2
/analysis/setFileName G4_Be9dn_SingleE.root

/gps/particle neutron

# the incident surface is in the x-y plane
/gps/pos/rot1 0 1 0
/gps/pos/rot2 1 0 0
#
# the beam spot is centered at the origin and is
# of 1d gaussian shape with a 3mm central plateau
/gps/pos/shape Circle
/gps/pos/centre 0. 0. 0. mm
/gps/pos/radius 1.5875 mm
/gps/pos/sigma_r 0 mm
#
# the beam is travelling along the z-axis with 5 degrees dispersion
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0
/gps/ang/type beam1d
#/gps/ang/sigma_r 0.018257970943255358 rad
/gps/ang/sigma_r 0.0273719346404061 rad


/gps/energy 0.328 MeV
/run/printProgress 100000
/run/beamOn 2000000
