/GasCell/GasCellPressure 1.9167 bar
/GasCell/GasCellPosition -20.635 cm
/GasCell/GasCellLength 3.03 cm
/GasCell/GasCellDiameter 0.635 cm
/Detectors/C7LYCDistance 5.9455 m
/Detectors/C6LYCDistance 5.9455 m
/Detectors/C7LYCTopcapPosition 4.5 mm
/Detectors/C7LYC_X 63 mm
/Detectors/C7LYC_Y 0. m
/Detectors/C6LYC_X -53.66 mm
/Detectors/C6LYC_Y 0. m
/Detectors/UseC6LYC true
/Detectors/UseC6LYC_Case true
/Detectors/UseC7LYC true
/Detectors/UseC7LYC_Case true
/Detectors/C6LYC_Slices 100
/Detectors/C7LYC_Slices 100
/Detectors/UseStructure true
/Detectors/UseDummy false
/Detectors/UseBe9Target true
/Detectors/UseLargeChamber true
/Detectors/UseLTC true
/Detectors/UseMTC true
/Detectors/UseGasCell false
/PartDist/EnergyAngleDist Eang_1.599.csv
/PartDist/EnergyZDist Ez_1.599.csv
/PartDist/EnergyAngleZBins EAngZ_1.599_bins.csv
/PartDist/NeutronsFile NeutronsData_1.599.csv
/PartDist/UseDists false
/PartDist/UseNeutrons false
/RunSettings/SaveVectors false
/Detectors/WorldMaterial G4_AIR

/run/useMaximumLogicalCores
#/run/numberOfThreads 6
/run/initialize
/control/verbose 2
/run/verbose 2
# Turn off multiple scattering
# /process/inactivate msc
/analysis/setFileName G4_Background_6m.root

/gps/particle neutron
/gps/number 1

# the incident surface is in the x-y plane
/gps/pos/rot1 0 1 0
/gps/pos/rot2 1 0 0
#
# the beam spot is centered at the origin and is
# of 1d gaussian shape with a 3mm central plateau
/gps/pos/type Point
#/gps/pos/shape Circle
/gps/pos/centre 0. 0. 0. mm
#/gps/pos/radius 1.25 cm
#/gps/pos/sigma_r 1.25 cm
#/gps/pos/type Volume
#/gps/pos/shape Cylinder
#/gps/pos/centre 0. 0. -20.635 cm
#/gps/pos/radius 0.3175 cm
#/gps/pos/halfz 1.515 cm
#
# the beam is travelling along the z-axis with 5 degrees dispersion
/gps/ang/type cos
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0
#/gps/ang/type beam1d
#/gps/ang/sigma_r 0.018257970943255358 rad
#/gps/ang/sigma_r 1.1811422567550731 rad
/gps/ang/maxtheta 0.02 rad

#/gps/ene/type User
#/gps/hist/type energy
#/gps/hist/point .05 0.
#/gps/hist/point 1.2 .25
#/gps/hist/point 12. .75

/gps/ene/type Lin
/gps/ene/min 50 keV
/gps/ene/max 12. MeV
/gps/ene/gradient 0.
/gps/ene/intercept 2.

/run/printProgress 100000
/run/beamOn 200000000
