/Detectors/C7LYCDistance 5.9455 m
/Detectors/C6LYCDistance 5.9455 m
/Detectors/C7LYC_X -63 mm
/Detectors/C7LYC_Y 0. m
/Detectors/C6LYC_X 53.66 mm
/Detectors/C6LYC_Y 0. m

/run/useMaximumLogicalCores
#/run/numberOfThreads 6
/run/initialize
/control/verbose 2
/run/verbose 2
/analysis/setFileName G4_Be9dn.root

/gps/particle neutron

# the incident surface is in the x-y plane
/gps/pos/rot1 0 1 0
/gps/pos/rot2 1 0 0
#
# the beam spot is centered at the origin and is
# of 1d gaussian shape with a 3mm central plateau
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0. 0. 0. mm
/gps/pos/radius 0.3175 cm
/gps/pos/sigma_r 0.3175 cm
#
# the beam is travelling along the z-axis with 5 degrees dispersion
/gps/ang/rot1 0 1 0
/gps/ang/rot2 1 0 0
/gps/ang/type beam1d
#/gps/ang/sigma_r 0.018257970943255358 rad
#/gps/ang/sigma_r 1.1811422567550731 rad
/gps/ang/sigma_r 0.03490658503988659 rad

/gps/ene/type User
/gps/hist/type energy
/gps/hist/point 3.707 0.00000
/gps/hist/point 3.733 0.00064
/gps/hist/point 3.760 0.00445
/gps/hist/point 3.787 0.01081
/gps/hist/point 3.813 0.01463
/gps/hist/point 3.840 0.00827
/gps/hist/point 3.867 0.02545
/gps/hist/point 3.893 0.02099
/gps/hist/point 3.920 0.03117
/gps/hist/point 3.947 0.03690
/gps/hist/point 3.973 0.03181
/gps/hist/point 4.000 0.03117
/gps/hist/point 4.027 0.03626
/gps/hist/point 4.053 0.03690
/gps/hist/point 4.080 0.04135
/gps/hist/point 4.107 0.04389
/gps/hist/point 4.133 0.04262
/gps/hist/point 4.160 0.05344
/gps/hist/point 4.187 0.03499
/gps/hist/point 4.213 0.04707
/gps/hist/point 4.240 0.06489
/gps/hist/point 4.267 0.04262
/gps/hist/point 4.293 0.06361
/gps/hist/point 4.320 0.02545
/gps/hist/point 4.347 0.02926
/gps/hist/point 4.373 0.04262
/gps/hist/point 4.400 0.06425
/gps/hist/point 4.427 0.05153
/gps/hist/point 4.453 0.04071
/gps/hist/point 4.480 0.02226
/gps/hist/point 4.507 0.00000



/run/printProgress 100000
/run/beamOn 2000000
